# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://opendataco.github.io
title: Colombia
email: dav.alejandro@gmail.com
author: Open Data Colombia
description: Open Data - Datos Abiertos para Colombia
copyright: ''
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/datosabiertosco
  - title: github
    url: https://github.com/OpenDataCo
  - title: mailing list
    url: https://groups.google.com/forum/#!forum/opendataco
